
spring:
  redis:
    #    redis 服务器地址
    host: 127.0.0.1
    #    服务器端口号
    port: 6379
    #    服务器密码
    password: 123456
    #    redis 库 默认0
    database: 1
    #    连接超时时间
    timeout: 1000ms
    jedis:
      pool:
        #        最大连接数
        max-active: 1024
        #        最大连接阻塞等待时间，单位毫秒，默认 -1ms
        max-wait: 10000ms
        #        最大空闲连接 默认8
        max-idle: 200
        #        最小空闲连接，默认0
        min-idle: 5
