spring:
  application:
    # 应用名称
    name: jpa

  # springboot - jpa 配置
  jpa:
    hibernate:
      # 自动生成数据库表（关键）
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    # 在控制台显示hibernate的sql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  # mysql 数据库连接配置（非常重要）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost.3306/springboot_jpa?serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  # 关闭 thymeleaf 的缓存
  thymeleaf:
    cache: false

server:
  port: 8080


