
server:
  port: 8081

#指定mapper.xml的位置
mybatis:
  mapper-locations: classpath*:com/mayuan/mapper/mapper/*.xml
  type-aliases-package: com.example.demo.entity

#数据库驱动和ip
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myspace5?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: 123456
  #redis设置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#为某个包目录下设置日志
logging:
  level:
    com.example: debug

